#+title: Dirección ip estatica
#+date: <2021-04-25 22:06>
#+filetags: linux

*** Descripción
   :PROPERTIES:
   :CUSTOM_ID: descripción
   :END:

El sistema está configurado para obtener de forma automática la
configuración de red (ip, máscara de red, servidores DNS, puerta de
enlace) a travéz del servicio DHCP. Sin embargo, si se quiere configurar
un sistema como servidor en una red es muy recomendable, por no decir
necesario, que el sistema tenga una dirección ip estática.

*** Configuración
    :PROPERTIES:
    :CUSTOM_ID: configuración
    :END:

Antes de cambiar la configuración, hay que detener la interfaz de red:

#+BEGIN_SRC 
    root@devuan:~# ifdown eth0
#+END_SRC

En devuan el archivo de configuración de las interfaces de red está en
*/etc/network/interfaces*

#+BEGIN_SRC 
      # This file describes the network interfaces available on your system
      # and how to activate them. For more information, see interfaces(5).
      # The loopback network interface
        auto lo
        iface lo inet loopback
      # The primary network interface
      # allow-hotplug eth0
      # iface eth0 inet dhcp
      # Static IP address
        auto eth0
        iface eth0 inet static
        address 192.168.1.100
        netmask 255.255.255.0
        network 192.168.1.0
        broadcast 192.168.1.255
        gateway 192.168.1.1
#+END_SRC

Además de la configuración anterior, también hay que indicar cual es la
dirección ip del servidor DNS que las aplicaciones utilizarán cuando
tengan que traducir un nombre de dominio. En esta configuración casera
se puede poner como servidor DNS la ip del router/modem ADSL, porque el
router se encargará de reenviar la consulta DNS a otro servidor cuando
no la pueda resolver. La configuración del servidor DNS se hace en el
archivo */etc/resolv.conf*, en el se incluye una linea como la
siguiente: nameserver 192.168.1.1

*** Verificación
   :PROPERTIES:
   :CUSTOM_ID: verificación
   :END:

El comando ifconfig muestra información detallada de la configuración de
las interfaces de red. Primero hay que activar la interfaz de red recién
configurada:

#+BEGIN_SRC
    root@devuan:~# ifup eth0
#+END_SRC

#+BEGIN_SRC
    root@devuan:~# ifconfig eth0
    eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
    inet 192.168.1.100  netmask 255.255.255.0  broadcast 192.168.1.255
    inet6 fe80::224:8cff:feb5:c5cd  prefixlen 64  scopeid 0x20<link>
    ether 00:24:8c:b5:c5:cd  txqueuelen 1000  (Ethernet)
    RX packets 1156081  bytes 815368327 (777.5 MiB)
    RX errors 0  dropped 0  overruns 0  frame 0
    TX packets 1429829  bytes 470645432 (448.8 MiB)
    TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
#+END_SRC

Para comprobar que la configuración del archivo */etc/resolv.conf* es
correcta y se ha aplicado bien, se utiliza el comando ping a un nombre
de dominio de internet

#+BEGIN_SRC 
    root@devuan:/home/martin# ping www.devuan.org
     PING www.devuan.org (46.105.191.76) 56(84) bytes of data.
     64 bytes from web.devuan.org (46.105.191.76): icmp_seq=1 ttl=48 time=727 ms
     64 bytes from web.devuan.org (46.105.191.76): icmp_seq=2 ttl=48 time=328 ms
     64 bytes from web.devuan.org (46.105.191.76): icmp_seq=3 ttl=48 time=317 ms
     64 bytes from web.devuan.org (46.105.191.76): icmp_seq=4 ttl=48 time=323 ms
     64 bytes from web.devuan.org (46.105.191.76): icmp_seq=5 ttl=48 time=310 ms
     64 bytes from web.devuan.org (46.105.191.76): icmp_seq=6 ttl=48 time=320 ms
     ^C
     --- www.devuan.org ping statistics ---
     6 packets transmitted, 6 received, 0% packet loss, time 7091ms
     rtt min/avg/max/mdev = 310.061/387.881/727.275/151.891 ms
#+END_SRC
