#+title: Mocp reproducir audio desde la terminal
#+date: <2020-12-19 20:21>
#+filetags: linux


MOC es un reproductor de audio fácil de manejar y ligero, ideal para
equipos con pocos recursos. La interfaz es similar a MC (Midnight
Commander, el administrador de archivos) MOC reproduce todos los
archivos en el directorio a partir del archivo seleccionado para lo que
no es necesario crear listas de reproducción. Es posible reproducir
varios archivos o directorios de archivos y después guardar lalista de
reproducción como un archivo con extensión m3u. Funciona como demonio,
es decir que se ejecuta en segundo plano por lo que no necesita entorno
gráfico. Esto quiere decir también que si necesitas usar la terminal, el
emulador de terminal ó cerrar el entorno gráfico no es necesario detener
la reproducción ya que ésta sigue activa en segundo plano. Soporta los
siguientes formatos: mp3, Ogg Vorbis, FLAC, Musepack, Speex, WAVE, AIFF
y AU entre otros. Soporta Internet stream. Soporta temas de
configuración.

** Instalación
   :PROPERTIES:
   :CUSTOM_ID: instalación
   :END:

#+BEGIN_SRC
    sudo apt install moc
#+END_SRC

Alternativamente se puede instalar un plugin para reproducir archivos en
formatos como WMA, RealAudio, MP4 y ACC.

#+BEGIN_SRC
    sudo apt install moc-ffmpeg-plugin
#+END_SRC

** Uso
   :PROPERTIES:
   :CUSTOM_ID: uso
   :END:

El binario tiene el nombre *mocp* para evitar problemas con otras
aplicaciones u otros sistemas.

La sintaxis en la siguiente:

#+BEGIN_SRC
    mocp [opciones] [archivo]
#+END_SRC

Las opciones principales son:

#+BEGIN_SRC
    -c --clear
       Limpia la lista de reproducción.

    -p --play
       Comienza a reproducir desde el primer elemento en la lista de reproducción.

    -f --next
       Cambia al siguiente elemento en la lista de reproducción.

    -r --previous
       Cambia al elemento anterior en la lista de reproducción.

    -s --stop
       Detiene la reproducción.

    -P --pause
       Pausa la reproducción.

    -U --unpause
       Quita la pausa en la reproducción..

    -G --toggle-pause
       Hace el cambio entre reproducir y pausa.

    -T --theme
       Usa un tema específico. De no ser una ruta completa el archivo será buscado en /usr/share/moc/themes, ~/.moc/themes y en el actual directorio.
#+END_SRC

Se puede lanzar sin parámetros para entrar a la interfaz de ncurses:

#+BEGIN_SRC
    mocp
#+END_SRC

Del lado izquierdo esta el navegador de archivos y del derecho la lista
de reproducción, se cambia entre una y otra usando la tecla de
tabulación. A continuación en la parte inferior se encuentran el mensaje
de información que muestra el estatus del reproductor, el volumen, el
tiempo total de reproducción, la información sobre la pista, tiempo
transcurrido, restante y total de la pista, los parámetros de sonido,
opciones y la barra de reproducción.

Los accesos rápidos del teclado pueden verse presionando "h" , aquí una
lista con los más utilizados:

#+BEGIN_SRC
    q              Oculta la interfaz de ncurses
    ENTER          Comienza la reproducción o entra al directorio
    Q              Cierra la aplicación por completo
    s              Detiene la reproducción
    n              Reproduce el siguiente elemento
    b              Reproduce el elemento anterior
    p SPACE        Pausa
    f              Cambia la opción de leer las etiquetas ó sólo nombrar el archivo
    S              Activa/desactiva la reproducción aleatoria
    R              Activa/desactiva el repetir la lista después de finalizada
    X              Activa/desactiva el reproducir el siguiente elemento automáticamente
    TAB            Cambia entre la lista de reproducción y el explorador de archivos
    l              Muestra sólo el explorador de archivos ó la lista de reproducción
    a              Agrega un archivo/directorio a la lista de reproducción
    d              Elimina un archivo de la lista de reproducción
    C              Limpia la lista de reproducción
    A              Agrega un directorio recursivamente a la lista de reproducción
    <              Decrementa el volumen en 1%
    >              Incrementa el volumen en 1%
    ,              Decrementa el volumen en 5%
    .              Incrementa el volumen en 5%
    V              Guarda la lista de reproducción
    x              Alterna los canales del mezclador
    K              Selecciona el anterior preset del ecualizador
    k              Selecciona el siguiente preset del ecualizador
#+END_SRC

** Directorio de configuración: ~/.moc
   :PROPERTIES:
   :CUSTOM_ID: directorio-de-configuración-.moc
   :END:

El archivo de configuración principal dentro del directorio *~/.moc* es
*config*, este archivo no es necesario para el usa de la aplicación,
pero si lo es para modificar las preferencias, no se crea durante las
instalación sino que hay que copiarlo desde
*/usr/share/doc/moc/examples/config.example.gz* y descomprimirlo en
*~/.moc*

#+BEGIN_SRC
    cp /usr/share/doc/moc/examples/config.example.gz ~/.moc
    cd ~/.moc
    gzip -d config.example.gz
    mv config.example config
#+END_SRC

Está muy bien documentado y realmente los cambios son a gusto.
Normalmente sólo es necesario cambiar unas cuantas líneas para tener
todo funcionando a gusto, por ejemplo las siguientes: Repeat = yes
Shuffle = yes SoundDriver = ALSA Theme = black\_theme

Los directorios por defecto para los temas son */usr/share/moc/themes* y
** ~/.moc/themes**. Es posible descargar temas de configuración, o
editarlo uno y guardarlo en uno de estos directorios. Básicamente cada
elemento tiene la siguiente estructura:

#+BEGIN_EXAMPLE
    elemento        = color-de-texto
    color-de-fondo  = atributos
#+END_EXAMPLE

Los colores permitidos son:

#+BEGIN_EXAMPLE
    default (sirve como transparencia)
    black
    red
    green
    yellow
    blue
    magenta
    cyan
    white
    grey
#+END_EXAMPLE

Los atributos le dan formato al texto y son:

atributo | función -|- normal | default (sin destacado) standout | mejor
salida underline | subrayado reverse | video inverso blink | parpadeo
dim | medio brillo bold | negrita protect | modo protegido

Ejemplo del archivo ** ~/.moc/themes/black\_themes** documentado:

#+BEGIN_SRC
    # Interfaz de ncurses
    background = red default
    frame = red default
    window_title = yellow default underline,dim

    # Archivos, directorios y listas de reproducción
    directory = yellow default
    selected_directory = yellow default underline
    playlist = yellow default
    selected_playlist = yellow default
    file = yellow default
    selected_file = yellow default underline
    selected_info           = yellow        default bold

    # Elemento que actualmente se está reproduciendo
    marked_file = yellow default bold
    marked_selected_file = red default bold,underline
    marked_info             = blue          default bold
    marked_selected_info    = cyan          default

    # Estatus
    info = yellow default
    status = yellow default
    title = yellow default
    state = yellow default

    # Tiempo
    current_time = yellow default
    time_left = yellow default
    total_time = yellow default
    time_total_frames = yellow default ~/.mo

    # Parámetros de sonido
    sound_parameters = yellow default
    legend = yellow default
    disabled = red default dim
    enabled = yellow default bold

    # Barra de Volumen
    empty_mixer_bar = yellow red
    filled_mixer_bar = red yellow

    # Barra de reproducción
    empty_time_bar = yellow default
    filled_time_bar = default yellow

    # Guardar lista de reproducción
    entry = yellow default
    entry_title = yellow default bold

    # Mensajes
    error = cyan default
    message = yellow default

    # Tiempo total de la lista de reproducción o directorio
    plist_time = yellow default
#+END_SRC

Para asociar un tema por default hay que editar el archivo de
configuración ~/.moc/config y editar la opción "Theme" de esta forma:
Theme = black\_theme

Es posible usar temas sin necesidad de editar el archivo de
configuración usando el parámetro *-T*: mocp -T tema\_a\_usar

También es posible cambiar el tema dentro de la misma interfaz ncurses
presionando *T* con lo que se desplegara un menú con los temas
disponibles.

** Ecualizador
   :PROPERTIES:
   :CUSTOM_ID: ecualizador
   :END:

Moc tiene la opción de utilizar un ecualizador pero necesita de algún
preset que por default no hay en la carpeta de configuración, estos
deben estar ubicados en la carpeta ** ~/.moc/eqsets*. Se puede crear uno
a mono pero lo más sencillo es descargarlos, en internet están
disponibles algunos presets convertidos de winamp o xmms en un archivo
*eqsets.tar.gz**. Para utilizarlos basta con:

#+BEGIN_SRC
    cd  ~/.moc/
    wget http://ftp.daper.net/pub/soft/moc/contrib/eqsets.tar.gz
    tar xvfz eqsets.tar.gz
    rm eqsets.tar.gz
#+END_SRC

Y ahora dentro de moc hay refrescar la lista de presets presionando *e*,
se cambia con *k* (minúscula) hacia adelante o con *K* (mayúscula) hacia
atrás.

*** Problemas frecuentes
    :PROPERTIES:
    :CUSTOM_ID: problemas-frecuentes
    :END:

Mensaje de error al lanzar MOC:

#+BEGIN_SRCh
    FATAL_ERROR: Can't send() int to the server. / FATAL_ERROR: Can't receive value from the server.
#+END_SRC

Basta con borrar el directorio ~/.moc/cache

#+BEGIN_SRCh
    rm -rf ~/.moc/cache
#+END_SRC

y lanzar de nuevo la aplicación.

*Fuentes* 
archivo recuperado del viejo esdebian
man moc
[[https://moc.daper.net/][Moc pagina oficial]]
