#+title: It's Magit!
#+date: <2021-04-04 23:45>
#+filetags: git

** ¿Que es magit?

  Magit es una interfaz de usuario completa basada en texto para Git . Llena la brecha evidente entre la interfaz de línea de comandos de Git y varias GUI, lo que le permite realizar tareas de control de versiones triviales y elaboradas con solo un par de pulsaciones de teclas mnemotécnicas.

  Magit parece una versión mejorada de lo que obtiene después de ejecutar algunos comandos de Git, pero en Magit cada bit de información visible también es procesable hasta un punto que va mucho más allá de lo que proporciona cualquier GUI de Git y se encarga de actualizar automáticamente esta salida cuando se vuelve obsoleto. En segundo plano, Magit solo ejecuta comandos de Git y, si lo desea, puede ver qué se está ejecutando exactamente, lo que le permite aprender la gitlínea de comandos usando Magit.
  
** Comenzando
   
   #+BEGIN_SRC 
     C-x g
   #+END_SRC

   Para mostrar información sobre el repositorio git actual en un buffer dedicado, llamado buffer de estado.

   La mayoría de los comandos de Magit se invocan habitualmente desde el buffer de estado. Se puede considerar la interfaz principal para interactuar con Git usando Magit. Pueden existir muchos otros buffers de Magit en un momento dado, pero a menudo se crean desde este buffer.

   Dependiendo del estado en el que se encuentre tu repositorio, este buffer puede contener secciones tituladas "Staged changes", "Unstaged changes", "Unmerged into origin/master", "Unpushed to origin/master", y muchas otras.

   Como estamos empezando desde un estado seguro, al que puedes volver fácilmente (haciendo un git reset --hard PRE-MAGIT-STATE), actualmente no hay cambios escalonados o no escalonados. Edita algunos archivos y guarda los cambios. Luego vuelve al buffer de estado, mientras que al mismo tiempo lo refrescas, escribiendo C-x g. (En el buffer de estado, o cualquier buffer Magit para el caso, es el buffer actual, entonces también puedes usar sólo g para refrescarlo).

  Desplácese entre las secciones utilizando p y n. Tenga en cuenta que los cuerpos de algunas secciones están ocultos. Escriba TAB para expandir o contraer la sección en cuestión. También puede utilizar C-tab para alternar la visibilidad de la sección actual y sus hijos. Desplácese a la sección de un archivo dentro de la sección denominada "Cambios no escenificados" y escriba s para escenificar los cambios que ha realizado en ese archivo. Ese archivo aparece ahora en "Cambios escenificados".

  Magit puede organizar y desorganizar bloques individuales, no sólo archivos completos. Muévete al archivo que acabas de escenificar, expándelo usando TAB, muévete a uno de los hunks usando n, y desescenifica sólo eso escribiendo u. Observa cómo los comandos de escenificación (s) y desescenificación (u) operan en el cambio en el punto. Muchos otros comandos se comportan de la misma manera.

| entrada  | salida                                             |
| -------- | -------                                            |
| C-x g    | Muestra info en buffer dedicado (buffer de estado) |
| g        | Actualiza el buffer de estado                      |
| p n      | Desplazarse entre secciones                        |
| TAB      | Expandir o contraer secciones                      |
| C-TAB    | Alternar visibilidad entre secciones e hijos       |
| s        | Agregar cambios al stage (git add .)               |
|          |                                                    |


