#+title: tmux
#+date: <2021-10-21 16:44>
#+description: multiplexor de terminal 
#+filetags: linux

** Wikipedia

tmux es un multiplexor de terminal para sistemas tipo unix, similar a
GNU Screen que permite dividir una consola en múltiples secciones o
generar sesiones independientes en la misma terminal. Permite crear
varias terminales dentro de una misma pantalla, las que incluso pueden
desacoplarse y volver a acoplar en una sesión distinta​. tmux utiliza un
modelo cliente-servidor. El servidor tiene varias sesiones y cada
ventana es una entidad independiente que puede ser libremente vinculado
a otras sesiones. En cada sesión se podrán visualizar y aceptar la
entrada de teclado de varios clientes.

** Configuración

El archivo de configuración es ~/.tmux.conf. Por defecto la combinación
de teclas básica es *C-b* que yo por comodidad la he cambiado por *C-a*
editando dicho archivo

** Comandos básicos
  

| bind-key                             | salida                                               |
|--------------------------------------+------------------------------------------------------|
| C-a %                                | Abre un panel vertical                               |
| C-a "                                | Abre un panel horizontal                             |
| C-a derecha-izquierda-arriba-abajo   | Cambiar al panel derecho, izquierdo, arriba, abajo   |
| C-a c                                | Crea una nueva pestaña                               |
| C-a ,                                | Darle nombre a la nueva pestaña                      |
| C-a n                                | Cambiar a la pestaña siguiente                       |
| C-a p                                | Cambiar a la pestaña previa                          |
| C-a ?                                | Lista de comandos                                    |
| C-a d                                | Salir de la sesión                                   |
| tmux a                               | Retomar la sesión                                    |

*** La wiki de arch tiene un muy buen ejemplo del archivo de configuración
   

#+BEGIN_SRC 
    # Mover las ventanas izquierda o derecha en la sesión
    bind-key -n C-right next
    bind-key -n C-left prev
    # Nueva combinacion Ctrl + z + (Las teclas a continuación abajo)
    set -g prefix C-z
    # Desatamos la tecla predeterminada Ctrl + b y utilizamos la nueva combinación Ctrl + z + [tecla] 
    unbind-key C-b
    bind-key C-z send-prefix
    # Nueva ventana
    bind-key C-n new-window
    # Dividir la ventana en forma horizontal
    bind-key C-h split-window -h
    # Dividir la ventana en forma vertical
    bind-key C-v split-window -v
    # Movernos al panel arriba
    bind-key C-up select-pane -U
    # Movernos al panel abajo
    bind-key C-down select-pane -D
    # Movernos al panel a la izquierda
    bind-key C-left select-pane -L
    # Movernos al panel a la derecha
    bind-key C-right select-pane -R
    # Ocultar la session para volver a entrar solo tipeamos en consola: tmux attach-session ó tmux attach
    bind-key C-d detach
    # Habilitar que el mouse selecciones los paneles
    set-option -g mouse-select-pane on
    set-option -g set-titles on
    # Sin actividad visual
    set -g visual-activity on
    set -g visual-bell on
    # Barra de estado
    set-option -g status-utf8 on
    set-option -g status-justify right
    set-option -g status-bg black
    set-option -g status-fg green
    set-option -g status-interval 5
    set-option -g status-left-length 30
    set-option -g status-left '#[fg=magenta]» #[fg=blue,bold]#T#[default]'
    set-option -g status-right '#[fg=cyan]»» #[fg=blue,bold] #[fg=magenta]%D %k:%M#[default]'
    set-option -g visual-activity on
    set-window-option -g monitor-activity on
    set-window-option -g window-status-current-fg green
    set-window-option -g clock-mode-colour white 
    set-window-option -g clock-mode-style 24
#+END_SRC

TODO Habilitar history y mouse

Fuentes:
[[https://wiki.archlinux.org/index.php/Tmux_(Español)][archwiki]]
[[https://hipertextual.com/archivo/2014/09/tmux/][hipertextual.com]]
