#+title: Dashboard, una pantalla de inicio extencible para emacs
#+date: <2021-02-10 09:09>
#+filetags: emacs

Pantalla de inicio practica y útil en *exwm*.

* Caracteristicas 
+ Muestra un banner de Emacs (editable).
+ Lista de archivos recientes.
+ [[/2020-12-21-emacs-bookmarks.html][Bookmarks]] list
+ Proyectos recientes (para esto usa [[/2020-12-07-projectile.html][projectile]] como dependencia)
+ Agenda org-mode
+ Lista de Registros

* Dependencias
Para que todo funcióne correctamente son necesarios los siguientes paquetes (disponibles en Melpa):

page-break-lines - https://github.com/purcell/page-break-lines
(optional) projectile - https://github.com/bbatsov/projectile
(optional) all-the-icons - https://github.com/domtronn/all-the-icons.el

* Instalación y uso
#+BEGIN_SRC 
M-x package-install RET Dashboard
#+END_SRC

#+BEGIN_SRC
(require 'dashboard)
(dashboard-setup-startup-hook)
;; Or if you use use-package
(use-package dashboard
  :ensure t
  :config
  (dashboard-setup-startup-hook))
#+END_SRC

En mi configuración personalizada todo esto y más se hace con use-package.

* Mi configuración

#+BEGIN_SRC 
;; Dashboard
(use-package dashboard
  :ensure t
  :custom
  (dashboard-banner-logo-title (format "Welcome to GNU/Emacs" user-full-name))
  (dashboard-startup-banner "~/storage/img/otra_estrella_min.png")
  (dashboard-items '((recents . 6)
		     (projects . 4)
	 	     (bookmarks . 4)
		     (agenda . 5)
		     
		     ))
  :config
  
  (setq dashboard-set-heading-icons t
	dashboard-set-file-icons t
	dashboard-set-init-info t
	dashboard-set-navigator t)
  
  (setq dashboard-navigator-buttons
	`((
	   (,(when (display-graphic-p)
	       (all-the-icons-octicon "home" :height 1.1 :v-adjust 0.0))
	    "FAQ" "El universo perdido de GNU/Emacs"
	    (lambda (&rest _) (browse-url "https://martiyo.github.io/faq")))
	   
	   (,(when (display-graphic-p)
	       (all-the-icons-material "home" :height 1.35 :v-adjust -0.24))
	    "Localhost" "Abrir minnotas.com"
	    (lambda (&rest _) (browse-url "http://misnotas.com/")))
	   
	   (,(when (display-graphic-p)
	       (all-the-icons-octicon "tools" :height 1.0 :v-adjust 0.0))
	    "Configuración" "Archivo de configuración de emacs"
	    (lambda (&rest _) (find-file (expand-file-name  "~/.emacs.d/init.el"))))
	   
	   (,(when (display-graphic-p)
	       (all-the-icons-octicon "list-ordered" :height 1.0 :v-adjust 0.0))
	    "TODO" "Abrir myTodo"
	    (lambda (&rest _) (find-file (expand-file-name  "~/org/myTodo.org"))))
	   
	   (,(when (display-graphic-p)
	       (all-the-icons-octicon "calendar" :height 1.0 :v-adjust 0.0))
	    "Agenda" "Agenda personal"
	    (lambda (&rest _)
	      (interactive)
	      (if (get-buffer "*Org Agenda*")
		  (progn
		    (switch-to-buffer-other-window "*Org Agenda*")
		    (kill-buffer "*Org Agenda*")
		    (org-agenda-list))
		(split-window-right)
		(org-agenda-list))))
	   
	   )))
  :hook
  (after-init . dashboard-setup-startup-hook))
#+END_SRC

*Fuentes* 

Esto es solo una guia que a la vez sirve como backup de la configuración que yo uso, la pagina de [[https://github.com/emacs-dashboard/emacs-dashboard][github de dashboard]] tiene la posta.

Esta configuración y otras muy útilies está [[https://gitlab.com/hefistion/emacs-config-with-lp/-/blob/master/emacs-configuracion.org][aquí]]
