#+title: El empaquetador tar
#+date: <2022-01-05 08:50>
#+description: 
#+filetags: linux

Empaquetar archivos y directorios. 

** Descripción

El programa tar, es usado para almacenar archivos y directorios en un solo archivo, no para comprimirlos. Dentro de los entornos Unix tar aparece como una orden que puede ser ejecutada desde la línea de órdenes de una consola de texto o desde un simple terminal.
Donde <archivoSalida> es el archivo resultado y <archivo1>, <archivo2>, etcétera son los diferentes archivos que serán "empaquetados" en <archivoSalida>. Este proceso permite respaldar archivos, compartirlos, transmitirlos por Internet o por redes locales de una forma fácil.

** Opciones más usadas
+ *-c* Crea un archivo tar que contiene los elementos especificados.
+ *-x* Extrae el archivo de almacenamiento al disco.
+ *-t* Listar el contenido del archivo tar.
+ *-f* Especifica el nombre del archivo de almacenamiento.
+ *-v* Visualizar lo que se realiza.
+ *-j* Se utiliza para comprimir el archivo a con de bzip2.
+ *-z* Se utiliza para comprimir el archivo a con de gzip.
*+ -r* Se utiliza para agregar o actualizar un archivo existente con archivos o directorios
+ *-u* Como -r, pero las nuevas entradas se agregan solo si tienen una fecha de modificación más reciente que la entrada correspondiente en el archivo.

** Ejemplos 

*****  Crear archivo tar sin comprimir

#+BEGIN_SRC
$ tar -cvf /path/to/foo.tar /path/to/foo/
#+END_SRC

Dónde ‘/path/to/foo.tar‘ es la ubicación del archivo tar resultante (con extención tar) y ‘/path/to/foo’ es la ubicación del archivo o directorio que se utilizará como entrada, las rutas pueden ser ralativas o absolutas.

***** Todos los archivos que comienzan con una letra

#+BEGIN_SRC 
# tar -cvf fullbackup.tar i*
install.log
install.log.syslog
#+END_SRC

*****  Agregar un archivo al tar existente

#+BEGIN_SRC 
# tar --append --file=backup.tar anaconda-ks.cfg
#+END_SRC

*****  Extraer archivos de un tar

#+BEGIN_SRC
$ tar -xvf /path/to/foo.tar
#+END_SRC

*****  Extraer archivos de un tar en un directorio especifico

#+BEGIN_SRC
$ tar -xvf /path/to/foo.tar -C /path/to/destination/
#+END_SRC

*****  Extraer un archivo del archivo tar

#+BEGIN_SRC
$ tar --extract -vv --occurrence --file=./backup.tar anaconda-ks.cfg
#+END_SRC

*****  Listar el contenido de tar

#+BEGIN_SRC
$ tar -ztvf /path/to/foo.tgz
#+END_SRC

*****  Crear, extraer y  listar un archivo .gz con tar

Crear

#+BEGIN_SRC
$ tar -czvf /path/to/foo.tgz /path/to/foo/
#+END_SRC

Extraer

#+BEGIN_SRC
$ tar -xzvf /path/to/foo.tgz /path/to/foo/
#+END_SRC

Listar 

#+BEGIN_SRC
$ tar -ztvf /path/to/foo.tgz /path/to/foo/
#+END_SRC

*****  Crear, extraer y listar  un archivo .bz2

Crear

#+BEGIN_SRC
$ tar -czvf /path/to/foo.tgz /path/to/foo/
#+END_SRC

Extraer

#+BEGIN_SRC
$ tar -xjvf /path/to/foo.tgz /path/to/foo/
#+END_SRC

Listar 

#+BEGIN_SRC
$ tar -jtvf /path/to/foo.tgz /path/to/foo/
#+END_SRC
